import fs from "fs";
import path from "path";
import { config } from "../config.js";
import type { InstallerFramework } from "./installerDetectionService.js";

export interface PsadtOptions {
  packageId: string;
  appName: string;
  appVersion: string;
  publisher: string;
  installerFileName: string;
  framework: InstallerFramework;
  silentSwitch: string;
  msiProductCode?: string;
  uninstallCmd: string;
  preScript?: string | null;
  postScript?: string | null;
  registryValues?: Record<string, { name: string; value: string; type?: string }> | null;
}

// ── Build install block based on installer type ───────────────────────────────

function installBlock(opts: PsadtOptions): string {
  const { installerFileName, framework, silentSwitch, msiProductCode } = opts;

  if (framework === "MSIX") {
    return `Add-AppxPackage -Path "$dirFiles\\${installerFileName}"`;
  }
  if (framework === "MSI" || installerFileName.toLowerCase().endsWith(".msi")) {
    return `Execute-MSI -Action 'Install' -Path "$dirFiles\\${installerFileName}" -Parameters '/QN /NORESTART REBOOT=ReallySuppress'`;
  }
  return `Execute-Process -Path "$dirFiles\\${installerFileName}" -Parameters '${silentSwitch}' -WindowStyle Hidden -IgnoreExitCodes '3010'`;
}

function uninstallBlock(opts: PsadtOptions): string {
  const { installerFileName, framework, msiProductCode, uninstallCmd } = opts;

  if (framework === "MSIX") {
    return `Get-AppxPackage -Name "*${opts.appName}*" | Remove-AppxPackage -ErrorAction SilentlyContinue`;
  }
  if ((framework === "MSI" || installerFileName.toLowerCase().endsWith(".msi")) && msiProductCode) {
    return `Execute-MSI -Action 'Uninstall' -Path '${msiProductCode}'`;
  }
  // Strip leading quoted path from uninstall cmd and use remaining args
  const args = uninstallCmd.replace(/^"[^"]*"\s*/, "").replace(/^[^\s]+\s*/, "").trim() || "/S";
  return `Execute-Process -Path "$dirFiles\\${installerFileName}" -Parameters '${args}' -WindowStyle Hidden`;
}

function registryBlock(values: PsadtOptions["registryValues"]): string {
  if (!values || Object.keys(values).length === 0) return "";
  return Object.entries(values)
    .map(([key, v]) =>
      `        Set-RegistryKey -Key '${key}' -Name '${v.name}' -Value '${v.value}' -Type '${v.type ?? "String"}'`
    )
    .join("\n");
}

// ── Main generator ────────────────────────────────────────────────────────────

export function generateDeployApplicationPs1(opts: PsadtOptions): string {
  const {
    appName, appVersion, publisher, installerFileName,
    framework, silentSwitch, preScript, postScript, registryValues,
  } = opts;

  const processName = appName.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
  const date = new Date().toLocaleDateString("en-GB");
  const ts = new Date().toISOString();

  return `<#
.SYNOPSIS
    PSADT v3 wrapper — ${appName} v${appVersion}
    Generated by AutoPack: ${ts}
    Framework: ${framework}
    DO NOT EDIT — regenerated on each AutoPack build
#>

[CmdletBinding()]
Param (
    [ValidateSet('Install','Uninstall','Repair')]
    [string]$DeploymentType   = 'Install',
    [ValidateSet('Interactive','Silent','NonInteractive')]
    [string]$DeployMode       = 'Interactive',
    [switch]$AllowRebootPassThru  = $false,
    [switch]$TerminalServerMode   = $false,
    [switch]$DisableLogging       = $false
)

Try {
    Try { Set-ExecutionPolicy -ExecutionPolicy 'ByPass' -Scope 'Process' -Force -ErrorAction 'Stop' } Catch {}

    ## Application metadata
    [string]$appVendor        = '${publisher}'
    [string]$appName          = '${appName}'
    [string]$appVersion       = '${appVersion}'
    [string]$appArch          = 'x64'
    [string]$appScriptDate    = '${date}'
    [string]$appScriptAuthor  = 'AutoPack'

    ## Dot-source PSADT toolkit (with graceful fallback if runtime is absent)
    [string]$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Definition
    [string]$toolkitPath = Join-Path $scriptDirectory 'AppDeployToolkit\\AppDeployToolkitMain.ps1'

    If (Test-Path $toolkitPath) {
        . $toolkitPath
    } Else {
        ## Fallback: PSADT runtime not bundled — execute installer directly
        If ($DeploymentType -eq 'Uninstall') {
            ${uninstallBlock(opts).replace("$dirFiles", '$(Join-Path $scriptDirectory "Files")')}
        } Else {
            ${installBlock(opts).replace("$dirFiles", '$(Join-Path $scriptDirectory "Files")')}
        }
        Exit 0
    }

    ##==========================================================================
    ## PRE-INSTALLATION
    ##==========================================================================
    [string]$installPhase = 'Pre-Installation'

    ## Welcome — close running instances, allow 3 deferrals, check disk space
    Show-InstallationWelcome -CloseApps '${processName}' -AllowDefer -DeferTimes 3 -CheckDiskSpace -PersistPrompt

    Show-InstallationProgress
${preScript ? `\n    ## Custom pre-install script\n    ${preScript.split("\n").join("\n    ")}` : ""}

    ##==========================================================================
    ## INSTALLATION
    ##==========================================================================
    [string]$installPhase = 'Installation'

    If ($deploymentType -ieq 'Install') {
        Write-Log -Message "Installing $appName v$appVersion" -Source $installPhase
        ${installBlock(opts)}
${registryBlock(registryValues)}
    }

    ##==========================================================================
    ## POST-INSTALLATION
    ##==========================================================================
    [string]$installPhase = 'Post-Installation'
${postScript ? `\n    ## Custom post-install script\n    ${postScript.split("\n").join("\n    ")}` : ""}
    Show-InstallationPrompt -Message "$appName v$appVersion installed successfully." -ButtonRightText 'OK' -Icon 'Information' -NoWait

    ##==========================================================================
    ## UNINSTALLATION
    ##==========================================================================
    [string]$installPhase = 'Uninstallation'

    If ($deploymentType -ieq 'Uninstall') {
        Show-InstallationWelcome -CloseApps '${processName}' -CloseAppsCountdown 60
        Write-Log -Message "Uninstalling $appName" -Source $installPhase
        ${uninstallBlock(opts)}
    }

    Exit-Script -ExitCode $mainExitCode
}
Catch {
    [int32]$mainExitCode = 60001
    Write-Log -Message "$(Resolve-Error)" -Severity 3 -Source $deployAppScriptFriendlyName
    Show-DialogBox -Text "$(Resolve-Error)" -Icon 'Stop'
    Exit-Script -ExitCode $mainExitCode
}
`;
}

export function writePsadtScript(packageId: string, content: string): string {
  const dir = path.resolve(config.UPLOADS_DIR, "psadt", packageId);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const scriptPath = path.join(dir, "Deploy-Application.ps1");
  fs.writeFileSync(scriptPath, content, "utf-8");
  return scriptPath;
}
